### ISSUE TITLE
Extract systemd class

### ISSUE THREAD

**Issue by domcleal** [sj26/puma-plugin-systemd#1]
Hi @sj26. I like the Systemd class you've created here for wrapping sd_notify - it'd be useful to me in other projects if it was a gem.

Would you like to co-maintain or maintain such a gem, or would you mind if I extracted and published it? It looks like the name `systemd` is available on rubygems.org.

**Comment by sj26** [comment]
You're welcome to use it! I want to keep this copy in here though to avoid extra dependencies and because it's super focused.

I don't think calling the gem `systemd` would be quite right, it's a very specific subset of integration. Maybe `systemd_notify`? But go nuts. :-)
