### ISSUE TITLE
puma (~> 3.6.0)

### ISSUE THREAD

**Issue by DSKonstantin** [sj26/puma-plugin-systemd#5]
Could update upgrade lock puma version?

```
Bundler could not find compatible versions for gem "puma":
  In snapshot (Gemfile.lock):
    puma (= 3.12.0)

  In Gemfile:
    puma (~> 3.12.0)

    puma-plugin-systemd was resolved to 0.1.1, which depends on
      puma (~> 3.6.0)

```

**Comment by ekohl** [comment]
https://github.com/sj26/puma-plugin-systemd/pull/7 would solve this, but is maybe a bit too permissive.

@sj26 could this get some attention? I'd like to use this plugin and this is blocking me. If needed, I'd be happy to help maintenance.

**Comment by sj26** [comment]
Sorry, this was done in #3 but was never released as a new gem version — I've just pushed one now.

**Comment by ekohl** [comment]
I appreciate that. We have upgraded to Puma 4 so I'll open a new issue for that.
